<?php
return apply_filters( 'ss_compatible_plugins', array(
	array( 'slug' => 'wordpress-seo' ),
	array( 'slug' => 'all-in-one-seo-pack' ),
	array( 'slug' => 'seo-by-rank-math' ),
	array( 'slug' => 'wp-seopress' ),
	array( 'slug' => 'google-sitemap-generator' ),
	array( 'slug' => 'elementor' ),
	array( 'slug' => 'essential-addons-for-elementor-lite' ),
	array( 'slug' => 'classic-editor' ),
	array( 'slug' => 'tinymce-advanced' ),
	array( 'slug' => 'updraftplus' ),
	array( 'slug' => 'duplicator' ),
	array( 'slug' => 'all-in-one-wp-migration' ),
	array( 'slug' => 'wp-mail-smtp' ),
	array( 'slug' => 'contact-form-7' ),
	array( 'slug' => 'wpcf7-redirect' ),
	array( 'slug' => 'google-site-kit' ),
	array( 'slug' => 'duplicate-post' ),
	array( 'slug' => 'duplicate-page' ),
	array( 'slug' => 'redirection' ),
	array( 'slug' => 'really-simple-ssl' ),
	array( 'slug' => 'limit-login-attempts-reloaded' ),
	array( 'slug' => 'insert-headers-and-footers' ),
	array( 'slug' => 'advanced-custom-fields' ),
	array( 'slug' => 'translatepress-multilingual' ),
	array( 'slug' => 'imagify' ),
	array( 'slug' => 'shortpixel-image-optimiser' ),
	array( 'slug' => 'webp-express' ),
	array( 'slug' => 'wp-optimize' ),
) );

