<?php
/**
 * @package Simply_Static
 */
?>

<h1><?php _e( 'Simply Static &rsaquo; Generate', Simply_Static::SLUG ); ?></h1>

<div class='wrap'>

	<?php wp_nonce_field( Simply_Static::SLUG ) ?>
	<input type='hidden' name='_generate' value='1' />

	<?php if ( $this->system_requirements_check_failed ) : ?>
		<p><?php _e( "Uh oh, we've found an issue that prevents us from creating a static copy of your site.", Simply_Static::SLUG ); ?></p>
	<?php endif; ?>

	<div class='actions'>
		<div class='action'>
			<p><?php _e( "Press the button below to create a static copy of your site.", Simply_Static::SLUG ); ?></p>
			<input id='generate' class='button button-primary button-hero <?php if ( ! $this->archive_generation_ready_to_start ) { echo 'hide'; } ?>' type='submit' name='generate' value='<?php _e( "Generate Static Files", Simply_Static::SLUG ); ?>' <?php if ( $this->system_requirements_check_failed ) { echo 'disabled=disabled'; } ?> />
		</div>

		<input id='pause' class='button button-hero hide' type='submit' name='pause' value='<?php _e( "Pause", Simply_Static::SLUG ); ?>' />

		<input id='resume' class='button button-primary button-hero <?php if ( $this->archive_generation_ready_to_start ) { echo 'hide'; } ?>' type='submit' name='resume' value='<?php _e( "Resume", Simply_Static::SLUG ); ?>' <?php if ( $this->system_requirements_check_failed ) { echo 'disabled=disabled'; } ?> />

		<input id='cancel' class='button button-cancel button-hero <?php if ( $this->archive_generation_ready_to_start ) { echo 'hide'; } ?>' type='submit' name='cancel' value='<?php _e( "Cancel", Simply_Static::SLUG ); ?>'  <?php if ( $this->system_requirements_check_failed ) { echo 'disabled=disabled'; } ?> />

		<span class='spinner'></span>
	</div>

	<h3><?php _e( "Activity Log", Simply_Static::SLUG ); ?></h3>
	<div id='activityLog'>
		<?php foreach ( $this->status_messages as $state_name => $status ) : ?>
			<div class='activity <?php echo $state_name; ?>'>[<?php echo $status['datetime']; ?>] <?php echo $status['message']; ?></div>
		<?php endforeach; ?>
	</div>

</div>









<!--
	<?php if ( is_array( $this->static_pages ) && count( $this->static_pages ) ) : ?>
		<?php $http_codes = array( '1' => 0, '2' => 0, '3' => 0, '4' => 0, '5' => 0 ); ?>
		<?php $num_errors = count( array_filter( $this->static_pages, function($p) { return $p->error_message != false; } ) ); ?>

		<h3><?php _e( 'Export Log', Simply_Static::SLUG ); ?></h3>
		<div class='export-log'>
			<table class='widefat'>
				<thead>
					<tr>
						<th><?php _e( 'Code', Simply_Static::SLUG ); ?></th>
						<th><?php _e( 'URL', Simply_Static::SLUG ); ?></th>
						<th><?php _e( 'Found on', Simply_Static::SLUG ); ?></th>
						<?php if ( $num_errors > 0 ) : ?>
						<th><?php echo sprintf( __( "Errors (%d)", Simply_Static::SLUG ), $num_errors ); ?></th>
						<?php endif; ?>
					</tr>
				</thead>
				<tbody>

				<?php
					function find_first_match( $static_pages, $id ) {
						foreach ( $static_pages as $static_page ) {
							if ( $static_page->id === $id ) {
								return $static_page;
							}
						}
					}
				?>

				<?php foreach ( $this->static_pages as $static_page ) : ?>
					<?php
						$digit = substr( $static_page->http_status_code, 0, 1 ); // get first digit of error code
						$http_codes[ $digit ] += 1;
					?>

					<tr>
						<td><?php echo $static_page->http_status_code; ?></td>
						<td><a href='<?php echo $static_page->url; ?>'><?php echo $static_page->url; ?></a></td>
						<?php $parent_static_page = find_first_match( $this->static_pages, $static_page->found_on_id ); ?>
						<td>
							<?php if ( $parent_static_page ): ?>
								<a href='<?php echo $parent_static_page->url; ?>'><?php echo $parent_static_page->url; ?></a>
							<?php else: ?>
								&mdash;
							<?php endif; ?>
						</td>
						<?php if ( $num_errors > 0 ) : ?>
						<td>
							<?php $msg = $static_page->error_message; if ( isset( $msg ) ) : ?>
								<?php echo __( $msg, Simply_Static::SLUG ); ?>
							<?php endif; ?>
						</td>
						<?php endif; ?>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>


		<p><?php _e( '1xx Informational:', Simply_Static::SLUG ); ?> <b><?php echo $http_codes['1']; ?></b> |
			<?php _e( '2xx Success:', Simply_Static::SLUG ); ?> <b><?php echo $http_codes['2']; ?></b> |
			<?php _e( '3xx Redirection:', Simply_Static::SLUG ); ?> <b><?php echo $http_codes['3']; ?></b> |
			<?php _e( '4xx Client Error:', Simply_Static::SLUG ); ?> <b><?php echo $http_codes['4']; ?></b> |
			<?php _e( '5xx Server Error:', Simply_Static::SLUG ); ?> <b><?php echo $http_codes['5']; ?></b> |
			<?php echo sprintf( __( "More information on HTTP status codes is available on <a href='%s'>Wikipedia</a>.", Simply_Static::SLUG ), 'https://en.wikipedia.org/wiki/List_of_HTTP_status_codes' ); ?></p>
		<hr />
	<?php endif ?> -->
