<?php
/**
 * @package Simply_Static
 */
?>

<h2><?php _e( 'Simply Static', $this->slug ); ?></h2>

<div class='wrap'>

	<?php if ( is_array( $this->export_log ) && count( $this->export_log ) ): ?>
		<?php $http_codes = array( '1' => 0, '2' => 0, '3' => 0, '4' => 0, '5' => 0 ); ?>

		<h3><?php _e( 'Export Log', $this->slug ); ?></h3>
		<div class='export-log'>
			<table class='widefat'>
				<thead>
					<tr>
						<th>Code</th>
						<th>URL</th>
						<th>Found on</th>
					</tr>
				</thead>
				<tbody>

				<?php foreach ( $this->export_log as $url => $data ) : ?>
					<?php
						$digit = substr( $data['code'], 0, 1 ); // get first digit of error code
						$http_codes[ $digit ] += 1;
					?>

					<tr>
						<td><?php echo $data['code']; ?></td>
						<td><a href='<?php echo $url; ?>'><?php echo $url; ?></a></td>
						<td><a href='<?php echo $data['source_url']; ?>'><?php echo $data['source_url']; ?></a></td>
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
		</div>


		<p><?php _e( '1xx Informational:', $this->slug ); ?> <b><?php echo $http_codes['1']; ?></b> |
			<?php _e( '2xx Success:', $this->slug ); ?> <b><?php echo $http_codes['2']; ?></b> |
			<?php _e( '3xx Redirection:', $this->slug ); ?> <b><?php echo $http_codes['3']; ?></b> |
			<?php _e( '4xx Client Error:', $this->slug ); ?> <b><?php echo $http_codes['4']; ?></b> |
			<?php _e( '5xx Server Error:', $this->slug ); ?> <b><?php echo $http_codes['5']; ?></b> |
			<?php echo sprintf( __( "More information on HTTP status codes is available on <a href='%s'>Wikipedia</a>.", $this->slug ), 'https://en.wikipedia.org/wiki/List_of_HTTP_status_codes' ); ?></p>
		<hr />
	<?php endif ?>

	<form id='generateForm' method='post' action=''>

		<?php wp_nonce_field( $this->slug ) ?>
		<input type='hidden' name='_generate' value='1' />

		<?php if ( $this->system_requirements_check_failed ) : ?>
			<p><?php _e( "Uh oh, we've found an issue that prevents us from creating a static copy of your site.", $this->slug ); ?></p>
		<?php else : ?>
			<p><?php _e( "Press the button below to create a static copy of your site.", $this->slug ); ?></p>
			<p><?php _e( "Note: on large sites this process may take a while.", $this->slug ); ?></p>
		<?php endif; ?>

		<p class='submit'>
			<input id='generate' class='button button-primary button-hero' type='submit' name='generate' value='<?php _e( "Generate Static Files", $this->slug );?>' <?php if ( $this->system_requirements_check_failed ) { echo 'disabled=disabled'; } ?> />
			<span class='spinner'></span>
		</p>

	</form>

</div>
